# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='User',
            new_name='user',
        ),
    ]
